# This notebook is to test the interface between NumPy-based and cuPyNumeric-based implementations of ExactBO

In [1]:
import tamubo.exactbo as ebo
import tamubo.utils as utils
import tamubo.acquisition_functions as acqfun
import cupynumeric as cp
import numpy as np

In [2]:
cpmu = cp.array([0.1, 0.2, 0.3])
cpsigma = cp.array([0.1, 0.2, 0.3])

npmu = np.array([0.1, 0.2, 0.3])
npsigma = np.array([0.1, 0.2, 0.3])

ymin = 0.0

cpei = acqfun.expected_improvement(cpmu, cpsigma, ymin)
#npei = ebo.expected_improvement(npmu, npsigma, ymin)

In [3]:
cpei

array([0.00833155, 0.01666309, 0.02499464])

In [4]:
tempcpei = acqfun.expected_improvement(cpmu, cpsigma, ymin, backend="cupynumeric")
tempnpei = acqfun.expected_improvement(npmu, npsigma, ymin, backend="numpy")

In [5]:
tempcpei, tempnpei

(array([0.00833155, 0.01666309, 0.02499464]),
 array([0.00833155, 0.01666309, 0.02499464]))

In [6]:
utils.resolve_backend()

BackendInfo(requested='auto', selected='cupynumeric', cupynumeric_available=True)

In [9]:
prueba = {}
prueba[1] = {"a": 1, "b": 2}

In [10]:
prueba[1].update({"c": 3})

In [11]:
prueba

{1: {'a': 1, 'b': 2, 'c': 3}}