In [1]:
from sklearn.datasets import make_friedman2
from sklearn.gaussian_process.kernels import RBF
from sklearn.gaussian_process import GaussianProcessRegressor
import numpy as np
import time
X, y = make_friedman2(n_samples=500, noise=0, random_state=0)
kernel1 = RBF()
start = time.time()
gpr1 = GaussianProcessRegressor(optimizer=None).fit(X, y)
y_pred1, y_cov1 = gpr1.predict(X[:2,:], return_cov=True)
print(time.time()-start)
y_pred1

0.014837980270385742


array([781.91445761, 518.4431357 ])

In [2]:
from kernels import rbf
from _gp import gpr

In [3]:
#kernel2 = rbf(0.5)
start = time.time()
gpr2 = gpr().fit(X,y)
y_pred2, y_cov2 = gpr2.predict(X[:2,:])
print(time.time()-start)
y_pred2

0.07944703102111816


tensor([[734.5406],
        [487.0322]])

In [4]:
kT = rbf()
KT = kT(X)
KT

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [5]:
kernel1(X)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
import torch
dists = torch.cdist(torch.Tensor(X),torch.Tensor(X),2)**2
torch.exp(-0.5*dists)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [26]:
from scipy.spatial import distance
import numpy as np
dists = distance.cdist(X,X, metric="sqeuclidean")
np.exp(-0.5 * dists)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [7]:
import torch
torch.Tensor(y).view(-1,1)

tensor([[ 781.9144],
        [ 518.4431],
        [ 603.1759],
        [ 129.4659],
        [1156.2297],
        [ 667.6761],
        [ 168.2909],
        [ 218.7709],
        [  49.7307],
        [1071.4923],
        [ 586.8406],
        [ 265.4374],
        [ 411.6558],
        [ 116.1811],
        [ 259.8901],
        [ 201.4477],
        [ 598.0249],
        [ 288.4382],
        [ 829.1324],
        [  99.4668],
        [  60.5027],
        [ 298.0407],
        [ 526.8176],
        [ 375.2657],
        [ 143.8872],
        [ 422.1528],
        [ 632.1334],
        [ 752.4409],
        [ 502.5814],
        [ 952.1691],
        [ 906.0633],
        [  47.4927],
        [ 376.3616],
        [ 349.6201],
        [ 779.9142],
        [ 328.9450],
        [ 151.1417],
        [ 272.1801],
        [ 141.0118],
        [ 437.2432],
        [ 629.5964],
        [  99.1716],
        [ 223.8016],
        [ 125.3582],
        [1157.0250],
        [ 658.7821],
        [ 611.7206],
        [ 263

In [10]:
import torch
torch.mps.device_count()

1

In [11]:
torch.mps.is_available()

True

In [12]:
device = torch.device('mps')

In [13]:
x = torch.Tensor([[1,2],[3,4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [14]:
x = x.to(device)
x

tensor([[1., 2.],
        [3., 4.]], device='mps:0')