In [1]:
%env PYTORCH_ENABLE_MPS_FALLBACK=1

env: PYTORCH_ENABLE_MPS_FALLBACK=1


In [2]:
from sklearn.datasets import make_friedman2
from sklearn.gaussian_process.kernels import RBF, ConstantKernel
from sklearn.gaussian_process import GaussianProcessRegressor
import numpy as np
import time
X, y = make_friedman2(n_samples=500, noise=0, random_state=0)
kernel1 = ConstantKernel(0.5)*RBF(0.5)
start = time.time()
gpr1 = GaussianProcessRegressor(kernel1,optimizer=None,alpha=0.1).fit(X, y)
y_pred1, y_cov1 = gpr1.predict(X[:2,:], return_cov=True)
print(time.time()-start)
y_pred1, y_cov1

0.02381420135498047


(array([651.59538141, 432.03594646]),
 array([[0.08333333, 0.        ],
        [0.        , 0.08333333]]))

In [3]:
from kernels import rbf
from _gp import gpr

In [4]:
kernel2 = rbf(0.5, 0.5)
start = time.time()
gpr2 = gpr(kernel2,0.1).fit(X,y)
y_pred2, y_cov2 = gpr2.predict(X[:2,:])
print(time.time()-start)
y_pred2, y_cov2

0.3833746910095215


/Users/juanesfco/tamubo/_gp.py:93: UserWarning: The operator 'aten::linalg_cholesky_ex.L' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
  self.L_ = torch.linalg.cholesky(K)


(tensor([[651.5953],
         [432.0359]], device='mps:0'),
 tensor([[0.0833, 0.0000],
         [0.0000, 0.0833]], device='mps:0'))

In [5]:
gpr2.get_hyper_params()

tensor([0.5000, 0.5000, 0.1000])